// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'firebase_options.dart';


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAth1NFHk1uYQ0my8dn0eMT05D_IVRoBF4',
    appId: '1:270490336900:web:607cb27660493abe144cd1',
    messagingSenderId: '270490336900',
    projectId: 'redsocia',
    authDomain: 'redsocia.firebaseapp.com',
    storageBucket: 'redsocia.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJ1kJd_tI9Jq_q-tld8AW1zB39h-FdUxM',
    appId: '1:559926376327:android:8780d1171a7a47addf0522',
    messagingSenderId: '559926376327',
    projectId: 'fa2808-d5431',
    storageBucket: 'fa2808-d5431.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcV1w7azYvyIdW4gv5mNvcIt3GIfb9DNE',
    appId: '1:270490336900:ios:14abc6cb33dfd0d6144cd1',
    messagingSenderId: '270490336900',
    projectId: 'redsocia',
    storageBucket: 'redsocia.firebasestorage.app',
    iosBundleId: 'com.example.redSocial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcV1w7azYvyIdW4gv5mNvcIt3GIfb9DNE',
    appId: '1:270490336900:ios:14abc6cb33dfd0d6144cd1',
    messagingSenderId: '270490336900',
    projectId: 'redsocia',
    storageBucket: 'redsocia.firebasestorage.app',
    iosBundleId: 'com.example.redSocial',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAth1NFHk1uYQ0my8dn0eMT05D_IVRoBF4',
    appId: '1:270490336900:web:64269999b4282859144cd1',
    messagingSenderId: '270490336900',
    projectId: 'redsocia',
    authDomain: 'redsocia.firebaseapp.com',
    storageBucket: 'redsocia.firebasestorage.app',
  );
}